[profile.default]
src = 'tests/foundry/LUKSOGenesitDepositContractTester.t.sol'
out = 'out'
libs = ['node_modules','lib']
cache_path = 'forge-cache'
test = 'tests/foundry'
solc_version = "0.8.15"
[fuzz]
runs = 100_000


