name: Run build + tests

on: [push]

env:
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
  COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY}}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.1"

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run build

      - name: Run tests
        run: npm test
